### Exercises
Try and finish these exercises with the help of the Introduction_to_Tensorflow notbook, or by using the Tensorflow documentation.
Only look at the solution, once you have finished trying to complete each exercise by yourself.

Before you can begin with any of these exercises, you need to import Tensorflow. Best use the common alias `tf`.

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

2. Find the shape, rank and size of the tensors you created in 1.

3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

4. Multiply the two tensors you created in 3 using matrix multiplication.

5. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

6. Find the min and max values of the tensor you created in 5.

7. Create a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

8. Now, get the tensor back to its original shape and dimensions.

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

### *Solutions*

In [1]:
import tensorflow as tf

2025-11-04 15:20:45.803983: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-11-04 15:20:45.804057: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-11-04 15:20:45.804831: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-11-04 15:20:45.811238: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.

In [2]:
vector = tf.constant([1,2,3])
vector

2025-11-04 15:20:48.088477: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1022 MB memory:  -> device: 0, name: NVIDIA A40, pci bus id: 0000:41:00.0, compute capability: 8.6


<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [3]:
scalar = tf.constant(2.)
scalar

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [4]:
matrix = tf.constant([[2,3],[4,5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [5]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                      [[7,8,9],
                       [10,11,12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

2. Find the nuber of dimenstions, shape, rank and size of the tensors you created in 1.

In [6]:
vector.ndim, vector.shape, tf.rank(vector), tf.size(vector)

(1,
 TensorShape([3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [7]:
scalar.ndim, scalar.shape, tf.rank(scalar), tf.size(scalar)

(0,
 TensorShape([]),
 <tf.Tensor: shape=(), dtype=int32, numpy=0>,
 <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [8]:
matrix.ndim, matrix.shape, tf.rank(matrix), tf.size(matrix)

(2,
 TensorShape([2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=2>,
 <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [9]:
tensor.ndim,tensor.shape, tf.rank(tensor), tf.size(tensor)

(3,
 TensorShape([2, 2, 3]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=12>)

3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [10]:
A = tf.random.uniform(shape=(5,300), minval=0, maxval=1)
B = tf.random.uniform(shape=(5,300), minval=0, maxval=1)

4. Multiply the two tensors you created in 3 using matrix multiplication.

In [11]:
tf.matmul(A,B, transpose_b = True)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[74.59535 , 75.60674 , 69.999084, 67.957275, 66.683304],
       [80.403885, 84.04361 , 77.43475 , 75.63266 , 76.066   ],
       [76.379486, 75.81778 , 74.89042 , 69.725746, 67.35031 ],
       [79.730606, 81.361   , 74.84615 , 71.6389  , 70.53766 ],
       [73.775024, 76.61779 , 71.595894, 68.08332 , 69.00787 ]],
      dtype=float32)>

5. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [12]:
C = tf.random.uniform(shape=(224,224,3), minval=0, maxval=1)
C

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.23698068, 0.60596013, 0.03490472],
        [0.21997666, 0.6906003 , 0.8030323 ],
        [0.6535144 , 0.9454063 , 0.8237027 ],
        ...,
        [0.40090644, 0.97601664, 0.6298902 ],
        [0.5994226 , 0.70292985, 0.8272102 ],
        [0.17318845, 0.362239  , 0.39615977]],

       [[0.07542503, 0.6988957 , 0.59502614],
        [0.6993222 , 0.89599   , 0.63963866],
        [0.9262625 , 0.5709777 , 0.31367993],
        ...,
        [0.8428457 , 0.18224871, 0.82805395],
        [0.72943056, 0.7028588 , 0.27285755],
        [0.12905109, 0.3489344 , 0.3299327 ]],

       [[0.26387715, 0.4020133 , 0.41976845],
        [0.34588397, 0.7689884 , 0.03951693],
        [0.6101475 , 0.31925762, 0.9470576 ],
        ...,
        [0.12478149, 0.3286457 , 0.2882552 ],
        [0.22218895, 0.5913515 , 0.7929268 ],
        [0.45744324, 0.9186493 , 0.11867285]],

       ...,

       [[0.28298998, 0.67876005, 0.04012513],
        [0.84

6. Find the min and max values of the tensor you created in 5.

In [13]:
tf.reduce_min(C)

<tf.Tensor: shape=(), dtype=float32, numpy=7.748604e-06>

In [14]:
tf.reduce_max(C)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999833>

7. Create a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [15]:
D = tf.random.uniform(shape=(1,224,224,3), minval=-100, maxval=9999)

In [16]:
D.shape

TensorShape([1, 224, 224, 3])

In [17]:
E = tf.squeeze(D)

In [18]:
E.shape

TensorShape([224, 224, 3])

8. Now, get the tensor back to its original shape and dimensions.

In [19]:
F = tf.expand_dims(E, -1)
F.shape

TensorShape([224, 224, 3, 1])

9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [20]:
G = tf.random.uniform(shape=(10,), minval = 0, maxval = 9, dtype = "int32")
G

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([8, 2, 2, 1, 1, 4, 3, 3, 1, 5], dtype=int32)>

In [21]:
tf.argmax(G)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

Well done!